### ISSUE TITLE
Basic Installation / Usage Example?

### ISSUE THREAD

**Issue by Simacho239** [maxschmeling/react-native-creativekit#1]
Thanks for pulling this package together!  Would it be possible to please see some basic installation instructions / an example usage to help us with integrating this?

**Comment by maxschmeling** [comment]
Yes, I plan to add a basic README soon. I put this together to solve a very specific need, but want to make it useful for others. If you `npm install` or `yarn add` and run `pod install` in your `ios` directory, it should all auto-link and *just work*.

**Comment by Simacho239** [comment]
Appreciate it - that'd be great.  Our build is compiling all fine, but the issue we're having is that the build is aborting on launch as it's trying to load the BitmojiKit framework as well, resulting in:

```
dyld: Library not loaded: @rpath/PINCache.framework/PINCache
  Referenced from: /Users/lewissimmons/Library/Developer/CoreSimulator/Devices/C99341C4-EBD1-495F-BC97-8538A969D720/data/Containers/Bundle/Application/25385440-D25A-48EC-8634-7A0BA99E9955/apprn.app/Frameworks/SCSDKBitmojiKit.framework/SCSDKBitmojiKit
  Reason: image not found
```

Have tried various ways to disable the framework being loaded (we don't need it) but no luck so far - have you come across this?

**Comment by Simacho239** [comment]
Appreciate it - that'd be great.  Our build is compiling all fine, but the issue we're having is that the build is aborting on launch as it's trying to load the BitmojiKit framework as well, resulting in:

```
dyld: Library not loaded: @rpath/PINCache.framework/PINCache
  Referenced from: /Users/{user}/Library/Developer/CoreSimulator/Devices/C99341C4-EBD1-495F-BC97-8538A969D720/data/Containers/Bundle/Application/25385440-D25A-48EC-8634-7A0BA99E9955/apprn.app/Frameworks/SCSDKBitmojiKit.framework/SCSDKBitmojiKit
  Reason: image not found
```

Have tried various ways to disable the framework being loaded (we don't need it) but no luck so far - have you come across this?

**Comment by maxschmeling** [comment]
I haven't. I'm surprised it's loading BitmojiKit since this is how the dependency is specified:
https://github.com/maxschmeling/react-native-creativekit/blob/b8f0f2a3cc69f97c017cb949915ec6d3d86b1bcc/react-native-creativekit.podspec#L33

Can you check your `podspec` in your local `node_modules/react-native-creativekit` and see if the dependency is referenced that same way? It's possible the NPM version is out of date.

**Comment by Simacho239** [comment]
I think BitmojiKit might have been loaded from another package.  What I'll do is try a clean setup without any preloaded SnapKit modules and see how that goes - will let you know.

When installing by either NPM or Yarn, both aren't installing the full package - they're only installing the license, package.json and readme.

**Comment by Simacho239** [comment]
Ok got it working!

So key things in case anyone else sees this / might help the readme:

- NPM + Yarn were not installing the full package, just the license package.json and readme - so I downloaded the package and manually added the missing files into the node_modules folder for this package
- This means that you also have to manually add the line `pod 'SnapSDK/SCSDKCreativeKit'` to your Podfile
- Within XCode, also need to ensure that the Objective-C Bridging Header within Build Settings points to the ReactNativeCreativeKit-Bridging-Header.h file

**Comment by maxschmeling** [comment]
Glad you got it figured out. I'll try to get this package up to date and better documented soon.

**Comment by thehappydinoa** [comment]
Hey man I am happy to help with documentation if you want a hand hmu
