### ISSUE TITLE
Instructions readme

### ISSUE THREAD

**Issue by WilliamBlais** [maxschmeling/react-native-creativekit#2]
Hi @maxschmeling ,

Thanks for creating this lib! Do you have any information on how to install it? Is it a manual linking process?

Thanks

**Comment by maxschmeling** [comment]
It's automatically linked and only works on iOS right now. Just `pod install` like normal.

Maybe I'll have time to really get this thing ready for the public before long... 🤷‍♂️

You're welcome to submit some README improvements.

Thanks
